### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by oliver-xapix-io** [iata-ndc/ndc-ruby-sdk#8]
Tried to deploy on Heroku. Has a Syntax error in your SDK. Here's Papertrail logs:

```
Oct 18 03:40:53 smart-cabin heroku/web.1:  State changed from crashed to starting 
Oct 18 03:40:58 smart-cabin heroku/web.1:  Starting process with command `bin/rails server -p 39960 -e production` 
Oct 18 03:41:00 smart-cabin app/web.1:  /app/vendor/bundle/ruby/2.0.0/bundler/gems/ndc-ruby-sdk-f726f6d17240/lib/ndc-client.rb:23:in `require_relative': /app/vendor/bundle/ruby/2.0.0/bundler/gems/ndc-ruby-sdk-f726f6d17240/lib/ndc-client/base.rb:81: syntax error, unexpected ':', expecting => (SyntaxError) 
Oct 18 03:41:01 smart-cabin app/web.1:  ...ERS.merge({'Authorization-Key': @rest_config['headers']['Aut... 
Oct 18 03:41:01 smart-cabin app/web.1:  ...                               ^ 
Oct 18 03:41:01 smart-cabin app/web.1:  /app/vendor/bundle/ruby/2.0.0/bundler/gems/ndc-ruby-sdk-f726f6d17240/lib/ndc-client/base.rb:81: syntax error, unexpected '}', expecting keyword_end 
Oct 18 03:41:01 smart-cabin app/web.1:  ...headers']['Authorization-Key']}) 
Oct 18 03:41:01 smart-cabin app/web.1:  ...                               ^ 
Oct 18 03:41:01 smart-cabin app/web.1:  	from /app/vendor/bundle/ruby/2.0.0/bundler/gems/ndc-ruby-sdk-f726f6d17240/lib/ndc-client.rb:23:in `<top (required)>' 
Oct 18 03:41:01 smart-cabin app/web.1:  	from /app/config/application.rb:4:in `require' 
Oct 18 03:41:01 smart-cabin app/web.1:  	from /app/config/application.rb:4:in `<top (required)>' 
Oct 18 03:41:01 smart-cabin app/web.1:  	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:78:in `require' 
Oct 18 03:41:01 smart-cabin app/web.1:  	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:78:in `block in server' 
Oct 18 03:41:01 smart-cabin app/web.1:  	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap' 
Oct 18 03:41:01 smart-cabin app/web.1:  	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server' 
Oct 18 03:41:01 smart-cabin app/web.1:  	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!' 
Oct 18 03:41:01 smart-cabin app/web.1:  	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>' 
Oct 18 03:41:01 smart-cabin app/web.1:  	from bin/rails:8:in `require' 
Oct 18 03:41:01 smart-cabin app/web.1:  	from bin/rails:8:in `<main>' 
Oct 18 03:41:01 smart-cabin heroku/web.1:  Process exited with status 1 
Oct 18 03:41:01 smart-cabin heroku/web.1:  State changed from starting to crashed 
```

**Comment by xurde** [comment]
The gem was not compliant with Ruby 2.0.0.
After commit bec9bed570b0d56dedf9bc98a1de0b5a6a2ec005 it is.

**Comment by oliver-xapix-io** [comment]
watch the deploy time. It's 17 mins ago...

**Comment by xurde** [comment]
Watch the error log. It's not the code currently in master branch.
https://github.com/iata-ndc/ndc-ruby-sdk/commit/bec9bed570b0d56dedf9bc98a1de0b5a6a2ec005#diff-38b7900649feb198f5dc54ffc219fa0bR81

I changed to old-style string-keys hashes supported since Ruby 1.9.

**Comment by oliver-xapix-io** [comment]
Not 100% sure, but GitHub will serve the latest TAGGED version of your library if one does not explitely tells it to fetch master. So here's two solutions:

- tag your current master as 0.1.1
- change your README to make people fetch `gem 'ndc-ruby-sdk', git: 'https://github.com/iata-ndc/ndc-ruby-sdk', branch: 'master'`

**Comment by xurde** [comment]
It's not Github, it's your cached local version.
You can reset you cached version by bundling without the gem and re-bundle with it again. (I think)
I would like to fix another platform related issue before releasing a new version (0.1.1)

**Comment by oliver-xapix-io** [comment]
Forcing Ruby 2.2.0 in Gemfile made it work for me. Still, 2.0.0 didn't seem to work out of the box on Heroku deployment... Not sure about version caching either... :/
